#!/bin/sh

cat <<EOF > .env
PUBLIC_STRIPE_KEY=$PUBLIC_STRIPE_KEY
SECRET_STRIPE_KEY=$SECRET_STRIPE_KEY
WEBHOOK_SIGNING_SECRET=$WEBHOOK_SIGNING_SECRET
DISCORD_WEBHOOK_URL=$DISCORD_WEBHOOK_URL
DISCORD_CLIENT_ID=$DISCORD_CLIENT_ID
DISCORD_CLIENT_SECRET=$DISCORD_CLIENT_SECRET
DISCORD_REDIRECT_URI=$DISCORD_REDIRECT_URI
DATABASE_URL=$DATABASE_URL
EOF

bunx prisma db push

bun run build

exec "$@"